### PR TITLE
Add UKF, PF, thermal-induced roll moment sensing, and much more...

### PR DESCRIPTION
**Pull request by philipoe**
This is a PR based on the Journal of Field Robotics article at http://onlinelibrary.wiley.com/doi/10.1002/rob.21765/full (for a free version of the paper click [here](http://www.atlantiksolar.ethz.ch/wp-content/downloads/publications/JFR_26hFlight_paper_2ndRev.pdf)). Note that this PR is still prototyping-code (as the code before was,too), but it significantly extends the functionality of the simulation framework.

**Contributions of this PR**

This PR
- Adds an Unscented Kalman Filter (UKF). _Requires / Based on Matlab 2016b's System-ID toolbox._
- Adds a Particle Filter (PF). _Requires / Based on Matlab 2016a's robotics toolbox_
- Adds a second measurement, i.e. the roll moment induced when flying through a thermal
- Adds data logging and plotting capability. 
- Adds scripted simulation capability (via ScriptedSimulation.... .m files). Also added parallel simulation capability of thermal test cases on multiple CPU cores. Together, these two features can be used to simulate hundreds of test cases with random initial conditions, thermal positions, waypoint tracks, parameters, etc. efficiently.
- Performs cleanup, bugfixing, drawing speedup
- Makes the GUI slightly nicer

**Sample visualization of how this looks now (uses the Particle Filter in this case)**

thermalsoar

_Note: I should have probably submitted this PR earlier and in smaller chunks. Given that it is that large now and considering that the Soaring_simulation is in general mostly a prototype-like environment, I suggest to this this PR mainly by just running the Matlab scripts instead of doing a super-detailed code review ..._

### CODE REVIEW

**Comment by samuelctabor** [comment]
Hi Philipp, thanks for the PR, lots of great functionality! I think the only thing I will change is to make the EKF  method able to run with a single measurement similar to the current implementation in ArduPlane. Should get it merged in the next week or so.
Cheers, Sam

**Comment by philipoe** [comment]
Hi Sam, thanks, good to know! About the "being able to run with a single measurement": My strategy was always that the measurement noise for z2 (i.e. the second measurement aka thermal-induced roll moment) can then simply be set to a very high value by the user, which effectively disables the measurement. See https://github.com/samuelctabor/Soaring_simulation/pull/2/files#diff-d33b95a8db01882541248756405bc584R60 . We could set this to a high (e.g. 10000.0) value by default. You don't think this is enough?

**Comment by samuelctabor** [comment]
I see, yes that makes sense. However I also use the same ExtendedKalmanFilter_thermal to replay flight data from the ArduPlane EKF, and for that the numerics need to be identical. I think I will just add a switch based on the number of elements in the input z.

**Comment by philipoe** [comment]
Sure...

**Comment by samuelctabor** [comment]
Hey Philipp, I have created a branch mergePhilipp with a couple of changes:
 - allows thermals position, strength and radius to be specified in Simulation constructor
 - allows ExtendedKalmanFilter_thermal to be called with a single measurement
 - resets some of the default parameters in Simulation.m and overrides them from ScriptedSimulation.
Could you check to see if you are happy that your model still works as before? If so I will merge.
Sam

**Comment by philipoe** [comment]
Seems good to me code-wise. I quickly fired up GUI.m and had a look, seemed to work OK, but of course I did not do any extensive tracking-quality checks with the now changed parameters anymore. It seemed to me that the tracking was a bit worse than before (e.g. because the initial uncertainty P_init o the KFs is now lower), but that might also be due to the 4-thermal setup that is the default now whereas I always just tested with a 1-thermal setup ... Anyways, the parameters are your choice.

**Comment by samuelctabor** [comment]
Merged!

**Pull request merged**
